CC=gcc
CFLAGS=-I -Wall -lpthread
DEPS=queue.h
cons: proc
	$(CC) -o cons src/cons.c $(CFLAGS)
proc:
	$(CC) -o proc src/proc.c src/queue.c $(CFLAGS)

proc:
	$(CC) -o proc src/NewToBinary.c $(CFLAGS)
proc:
	$(CC) -o proc src/NewtoAscii.c $(CFLAGS)
clean:
	rm *.output proc cons
	/